stages:
  - dockerbuild-push

variables:
  DOCKER_BUILDKIT: 1
  CI_DOCKER_IMAGE:  ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  CI_DOCKER_TAG:    ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  CI_DOCKER_BRANCH: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  CI_DOCKER_LATEST: ${CI_REGISTRY_IMAGE}:latest

package:
  image: docker:latest
  stage: dockerbuild-push
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
      # Create a new docker context for builder instance to use
    - docker context create builder-context
      # Create a builder instance named "builderx"
    - docker buildx create --name builderx --driver docker-container --use builder-context
  script:
    - docker build --platform linux/arm64/v8 --pull -t ${CI_DOCKER_LATEST} .
    - docker push  ${CI_DOCKER_LATEST}
  after_script:
    - docker logout