###################################################################################################
##  
##  Record for Geun
##  Your Server CPU Architecture : arm64/v8 (aarch64)
##  So You have to build for Cross Platform :)!
##  
###################################################################################################

# stages: Define task stage order
# ex) Proceed in order docker-build >>> docker-push
stages:
  # Build have to distributed for deployment rate 
  - docker-build
  - docker-push

# Set env
# $CI_PROJECT_NAME / $CI_COMMIT_TAG
# ImageTag's default tag == latest
variables:
  # For Image tag var
  CI_DOCKER_IMAGE:  ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  CI_DOCKER_TAG:    ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  CI_DOCKER_BRANCH: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  CI_DOCKER_LATEST: ${CI_REGISTRY_IMAGE}:latest

  CI_DOCKER_ARM64_LATEST: ${CI_REGISTRY_IMAGE}_ARM64:latest
  CI_DOCKER_AMD64_LATEST: ${CI_REGISTRY_IMAGE}_AMD64:latest
  CACHE_IMAGE_NAME: "$CI_REGISTRY/mygroup/$PROJECT_NAME/$PROJECT_NAME:cache"
  # For buildx activate
  DOCKER_BUILDKIT: 1

# Set Base Image
image: docker:latest

services:
  - docker:dind

###################################################################################################

before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
      # Create a new docker context for builder instance to use
    - docker context create builder-context
      # Create a builder instance named "builderx"
    - docker buildx create --name builderx --driver docker-container --use builder-context

after_script:
  - docker logout

###################################################################################################
## Parallel Operation (amd64 / arm64)
# Build for amd64
build_amd64:
  stage: docker-build
  script:
    - docker buildx build --platform=linux/amd64 --pull --push -t ${CI_DOCKER_LATEST} .

# Build for arm64
build_arm64:
  stage: docker-build
  script:
    - docker buildx build --platform=linux/arm64 --pull --push -t ${CI_DOCKER_LATEST} .

push:
  stage: docker-push
  script:
    # Push to Gitlab registry
    - echo ${CI_DOCKER_LATEST}
    - docker push ${CI_DOCKER_LATEST}

###################################################################################################