# Base Setting #
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

#########################################################

# Spring boot #

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  ## DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080
    username:
    password:

  ## JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

  ## JWT
  jwt:
    token:
      secret:

#########################################################